### ISSUE TITLE
Global updates

### ISSUE THREAD

**Issue by djm** [yunojuno/django-anonymise#1]
Potential idea I want to jot down before I forget about it.

Iteration and per-instance value generation is great because of the power it can wield in generating realistic data. However in some instances we do not need to use this power and a simple bulk update of the entire queryset with a static value would suffice and complete at a much faster speed than iteration.

We could look at introducing some from of "global" decorator for the anonymisation methods such that those ones are plucked out ahead of time (or after) and applied en-masse to the queryset after running the value generation (anon method) once for the entire queryset.

**Comment by hugorodgerbrown** [comment]
Aha. Yes - and I think this is pretty easy to do.

I have mulling over this at the weekend but never got around to writing it
up. I want to rename the bulk anon as "redaction" - so we have "restore",
"redact", "truncate" and "anonymise".

**Comment by djm** [comment]
There is also another arm to this.

Doing something which creates dynamic data with:

```
YourModel.objects.update(po_number=Concat(Value('PO-'), F('id')))
```

for example would be much faster than:

```
for object in YourModel.objects.all():
    object.po_number = f"PO-{obj.id}"
```

which is what we're effectively doing with these.

I guess what I'm saying is there is lots of space here to speed things up even with dynamic data.

**Comment by hugorodgerbrown** [comment]
The plan is to have `redact_FIELD_NAME` class properties that can be a fixed value or a callable. I have added a custom db Func called `GenerateUuid4` as an example - it gets around the whole "same uuid for all rows" issue:

```python
User.objects.update(uuid=GenerateUuid4())
```
generates SQL that looks like:
```sql
UPDATE user SET uuid=uuid_generate_uuid4();
```
Which is a Postgres operation only.

Building on this there is no reason why we can't do the same with F expressions like you suggest.

**Comment by hugorodgerbrown** [comment]
```python
@register_anonymiser
class UserAnonymiser(BaseAnonymiser):
    model = User

    redact_first_name = "FIRST_NAME"
    redact_last_name = "LAST_NAME"
    redact_uuid = GenerateUuid4()
    redact_public_id = Concat(Value('PO-'), F('id')))

```
generates SQL:
```sql
UPDATE
  user
SET
  first_name='FIRST_NAME',
  uuid=uuid_generate_uuid4(),
  public_id='PO-' || "id"
;
```

**Comment by hugorodgerbrown** [comment]
Redaction is then:
```python
anonymiser = UserAnonymiser()
anonymiser.redact_queryset(User.objects.all())
```
